### ISSUE TITLE
[zod-mock] Customizing mock options for array schema

### ISSUE THREAD

**Issue by ntucakovic-godaddy** [anatine/zod-plugins#105]
I'm wondering how to approach customizing mock response on a more complex schema that might include multiple arrays in one object. For instance (pseudo code)

```js
const schema = zod.object({
  items1: zod.array(zod.object({ a: number })),
  items2: zod.array(zod.object({ b: string }))
})
```

I would like to be able to set the length of both items1 and items2 arrays separately, for instance such as:
```js
const mock = generateMock(schema, {
  mockOptions: {
    items1: {
      length: 10,
    },
    items2: {
      length: 5,
    }
  }
})
```

I see that there's a possibility to rely on .length()/.min()/.max() right in the schema definiton, but it seems like for mocking purposes it might be better to avoid repeating the schema but rather be able to adjust options such as these?

I suppose there's a similar need for other types of data that might allow passing options to faker methods too?

Is there a past issue where this topic might have been discussed? I'm open to creating a PR for it if we can decide on the API signature.

Thanks

**Comment by Brian-McBride** [comment]
I think the idea of zod-mock is for quick and "easy" mocks. Just going fast. Once you start to need more detail, it is probably better to weave in faker directly. 
You could use lib like [ts-deepmerge](https://www.npmjs.com/package/ts-deepmerge) to blend your "manual" mock data with your auto-generated mock. Or just override those individual keys in your object with your own faker values. 

But, if you have an idea for an easy to define/maintain option structure and want to drop in a PR, that's super welcome!

**Comment by ntucakovic-godaddy** [comment]
I've went that road because I figured that would be the fastest bet to unblock the effort I'm working on.

I would like to provide contribute with a way to override any type of zod schema tho, the same way stringMap is working.

e.g.

```js
valueMap: {
  dueDate: () => faker.date.future().toISOString(),
  totalTasks: () => faker.datatype.number({ min: 5, max: 10 }),
  completedTasks: () => faker.datatype.number({ min: 0, max: 5 }),
},
```

Would you accept such an addition @Brian-McBride ?

**Comment by Brian-McBride** [comment]
Hi. Sorry for the long reply. 

Yes. There is a default mapping file for any key/value:
https://github.com/anatine/zod-plugins/blob/main/packages/zod-mock/src/lib/zod-mockery-map.ts

Not just string mapping. You can go wild with it and put in your own. It might help others to put in default values that are expected if the logic fails. Keep in mind, this is just walking through the Faker functions looking for name maps. If a function name is in `image` and then elsewhere, it might grab the image mock because of alphabetical order. Just today I added `city` so that it pulls from the city name instead of the city image. 

I wish Faker was using less of an object structure to more of a big function list. `locationCity()` would be better than `locaiton.city()` for this purpose.
