### ISSUE TITLE
[zod-mock] Refinements, regex and other toppings

### ISSUE THREAD

**Issue by Lzok** [anatine/zod-plugins#12]
Hi! How are you?
This library is great!

I am testing some things and I came across some scenarios that are "not mocked correctly" (maybe it is not the intention of the plugin). Is there any trick to do or it is out of scope of this plugin?

This will generate a common string instead of a "regexed" string
```javascript
const HEXCOLOR = new RegExp('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$');
const colorHex = z.string().regex(HEXCOLOR);
const color = generateMock(colorHex);
```

In this case, I want to mock valid MongoDB ids, and again, the mock generates common strings:
```javascript
import { Types } from 'mongoose';

function isValidObjectId(id: string) {
	if (Types.ObjectId.isValid(id)) {
		if (String(new Types.ObjectId(id)) === id) return true;
		return false;
	}
	return false;
}

const _id = z.string().refine((str: string) => isValidObjectId(str), {
	message: 'Invalid id.',
});
```

Thank you for your great work!

**Comment by Brian-McBride** [comment]
Hi @Lzok 

There are a few things going on here. The auto-mocking of this lib assumes that you are trying to mock out a base `z.object({})` so you'll need to consider that `const color = generateMock(colorHex);` probably won't work great. 

But, you might try: `const { color: colorHex } = generateMock(z.object( { colorHex } ));`

Here is what happens under the hood. The code iterates through the object keys (which is why a base object is needed) and looks for a function name in `faker` that matches the key you have. Unfortunately, there is no colorHex function and I am concerned that color will map to `company.color` as opposed to `internet.color` which is probably what most people would want. 

Luckily, there is a string lookup that checks your keys against some predefined strings:
https://github.com/anatine/zod-plugins/blob/a05e8fc31e825aa8f1db921babd6249d0e3f775b/libs/zod-mock/src/lib/zod-mock.ts#L38

I'll go ahead and add in a bunch of common color strings to match possible key names based on common CSS color names. It should push out to NPM here shortly.

In the future, maybe it might be useful to have an options argument that you can pass in `generateMock(z.object(), options)` that could expand that lookup table? Could be handy. Maybe even let you drop your own function in there too. 

Of course, in your use case `const color = faker.internet.color()` is so easy, maybe using this Mock lib is overkill. It is really useful when you have a large object. And even then you can override:

```typescript
const schema = z.object({
      uid: z.string().nonempty(),
      theme: z.enum([`light`, `dark`]),
      email: z.string().email().optional(),
      phoneNumber: z.string().min(10).optional(),
      avatar: z.string().url().optional(),
      jobTitle: z.string().optional(),
      otherUserEmails: z.array(z.string().email()),
      stringArrays: z.array(z.string()),
      stringLength: z.string().transform((val) => val.length),
      numberCount: z.number().transform((item) => `total value = ${item}`),
      age: z.number().min(18).max(120),
      userFavoriteColor: z.string().regex(new RegExp('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')),
    });

const mockData = generateMock(schema);

// override that color value!
mockData.userFavoriteColor = faker.internet.color();
```

It's a second step.

**Comment by Lzok** [comment]
Thanks for the insights!

>In the future, maybe it might be useful to have an options argument that you can pass in generateMock(z.object(), options) that could expand that lookup table?

That option would be nice, I think for both expand the lookup table and to provide a custom generator for a certain key if you want. For example in cases you need strings or numbers with min and max, or some data with custom refinement.

Yesterday I was reading about this topic and I found an interesting approach "type-safe". It requires work for the consumer side but I think it is useful and scalable. Maybe this weekend I can play with that + zod-mock to see if I could do something useful.

Example code in plain ts (source https://github.com/davelosert/mock-factory-pattern/blob/main/src/createMockTodo.ts):
```typescript
import cloneDeep from 'lodash.clonedeep';
import { createMockUser } from './createMockUser';
import { Todo } from './Todo';

const defaultTodo: Todo = {
  title: 'Default Todo Title',
  done: false,
  assignee: createMockUser(),
  dueDate: new Date('2021-07-04'),
  project: 'Writing Blogposts',
  tags: ['writing', 'blogs']
}

const createMockTodo = (overwrites: Partial<Todo> = {}) => {
  return cloneDeep({
    ...defaultTodo,
    ...overwrites
  });
};

export {
  createMockTodo
}
```

Maybe I'm thinking too much but at least I'll try to combine that approach with this plugin to see the results. What do you think?

**Comment by Brian-McBride** [comment]
THis is a bit old, but I think we might have solved this by adding in a default mapping file. 

https://github.com/anatine/zod-plugins/blob/main/packages/zod-mock/src/lib/zod-mockery-map.ts

Please feel free to add to the common keys to common values mappings. PR away, these would be easy wins and unlike string mapping, this will map keyname to whatever function. So they could be pretty extensive. 

Like, a map could be:

```ts
{
  dueDate: fakerInstance.date.anytime,
  dueDates: fakerInstance.helpers.arrayElement( Array.from(Array(100)).map(() => fakerInstance.date.anytime()))
}
```
