### ISSUE TITLE
[zod-mock] fully support bigint

### ISSUE THREAD

**Issue by joemays** [anatine/zod-plugins#132]
Current implementation returns numbers that are ints; should return instances of BigInt. 

See https://fakerjs.dev/api/number.html#bigint

**Comment by Brian-McBride** [comment]
I am not sure everyone wants to have a BigInt? 
The faker docs you linked start with `For simple integers, use int()`

If you need otherwise though, you can drop in your own mapper. Check out the section on Adding a custom mock mapper` in the README

You could easily create your won with whatever key mapping to `faker.number,bigInt()`

**Comment by joemays** [comment]
Sorry, perhaps I wasn't clear.  Zod schemas can specify bigints:
https://zod.dev/?id=bigints

...so was thinking that the use of `z.bigint()` in someone's Zod schema would indicate that they expect a bigint instance, not a number that's an int.

Regardless, I'll check out the link and thanks for looking into this.
