### ISSUE TITLE
findMatchingFaker matches images.city instead of location.city

### ISSUE THREAD

**Issue by jacobdubailcadmv** [anatine/zod-plugins#136]
I have a schema:

`
export const addressSchema = z.object({
	streetAddress: z.string(),
	secondaryAddress: z.string().optional(),
	city: z.string(),
	state: z.string(),
	zipCode: z.string(),
	default: z.boolean(),
});
`

My logs outputs: 

`[@faker-js/faker]: faker.image.city is deprecated since v8.0 and will be removed in v9.0. Please use faker.image.urlLoremFlickr({ category: 'city' }) or faker.image.url instead.`

Looking at the `findMatchingFaker` function, it seems like the mapping logic matches "images" before "location" even though I get a city name output in the resultant data.

**Comment by Brian-McBride** [comment]
Here is the reason. 
This walks through Faker's internal functions. And it looks for a matching function name. 
It used to work better when all faker's functions were in one huge list. But they have been creating sub-lists. 

`i` comes before `l` so it finds the key `city` in mages before. 
We could put a manual map in for that string key. Because this is likely to happen a lot, there is a map file exactly for that use.

https://github.com/anatine/zod-plugins/blob/main/packages/zod-mock/src/lib/zod-mockery-map.ts
That is the 3rd param in the mock gen function. 

Since it makes more sense to match city, I'll add in `city: fakerInstance.location.city` but if you see other logic issues, please drop in more maps in a PR. And on the short term, you can add them into your own mockeryMapper. 

I'll get a release out here in just a min.

**Comment by Brian-McBride** [comment]
Fixed: https://www.npmjs.com/package/@anatine/zod-mock
