### ISSUE TITLE
[zod-openapi] generateSchema creates incorrect schema type 

### ISSUE THREAD

**Issue by ilia373** [anatine/zod-plugins#192]
generateSchema creates incorrect schema type:

according to specification type field:
![image](https://github.com/anatine/zod-plugins/assets/5318003/6b2bfa09-d196-4004-b619-e2d0e125e269)

generated schema type field as array:
![image](https://github.com/anatine/zod-plugins/assets/5318003/5c5f6d68-f00f-4186-94ef-e51402a9652b)

swagger reports unknown type field:

![image](https://github.com/anatine/zod-plugins/assets/5318003/0ecb464f-b5ca-4f02-8ff5-5728fba8fc2e)

used versions:

"@anatine/zod-openapi": "^2.2.0",
"zod": "^3.22.4",
"@fastify/swagger": "^8.14.0",
"@fastify/swagger-ui": "^3.0.0"

node v21.2.0

**Comment by aslansky** [comment]
Same problem here. The change was introduced in 2.2.5. Works with version 2.2.4. For example the parseObject function in [zod-openapi.ts](https://github.com/anatine/zod-plugins/blob/main/packages/zod-openapi/src/lib/zod-openapi.ts#L200) now returns `type: ['object' as SchemaObjectType]` before it was just `type: "object"`.  But not sure if this is the problem.

**Comment by kerolloz** [comment]
Try to use openAPI version 3.1.0

**Comment by adambrgmn** [comment]
Hey, I just encountered this issue as well. Fortunately I was able to catch it. But it is a pretty significant change to introduce in a patch version bump.

At the same time I want to say that I'm otherwise very happy with these packages, and it has helped us a lot! So no shadow upon the maintainers, I know the struggle! I just want to know the reasoning behind change and what we need to do to handle it on our end, if there is anything? 

I'm not really sure what @kerolloz mean with testing openAPI v3.1.0?

The code example in this repo (`SwaggerModule.createDocument(app, new DocumentBuilder().build())` output a swagger schema with openapi version 3.0.0. And as far as I know there's no way to modify this or tell it to adhere to another version of the schema.

I'm happy to provide a PR to revert this if it would be appreciated.

**Comment by adambrgmn** [comment]
I see the changes were introduced in #173. And after reading thru the discussions I understand the desire from some teams to use this. But at the same time I wonder if there's anything that could be done to support multiple version maybe? Or maybe revert this for the 2.2 version line and release it in v3 (or if need be v2.3.0)?
