### ISSUE TITLE
`zod-mock`: ability to set the seed

### ISSUE THREAD

**Issue by sneko** [anatine/zod-plugins#76]
Hi @Brian-McBride ,

I would like to know if there is a way to pass the seed to faker.js to get the exact same results as done in the official library?
https://github.com/faker-js/faker/blob/next/src/faker.ts#L288-L295

From what I see it's not possible:
https://github.com/anatine/zod-plugins/blob/main/packages/zod-mock/src/lib/zod-mock.ts#L473-L504

Thank you,

EDIT: for more context, it would help during my tests (due to snapshots...). Passing it manually could be annoying, maybe an environment variable otherwise would do the trick, I did not see this in the official library.

**Comment by Brian-McBride** [comment]
Sure, that shouldn't be too hard. 
Always feel free to submit PRs. But I'll take a look and see if I can add this in quickly

**Comment by Brian-McBride** [comment]
A seed option is added for generating mock values. I didn't pull in an environment variable as that wouldn't work on the browser side, and I think Faker can run there too.

Maybe as another option, I can add dropping in your own Faker class so that you can modify it all you want and the code will use that one to generate everything.

**Comment by algoflows** [comment]
Hey guys is there a way to generate consistent mock results? 

options: {
  consistent: true
  }
  
  ?
